@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

'@@author zengzihui
start
:User executes addBuyer command;

if () then ([User provided correct parameters])
:Buyer's name, phone, email, budget and preferredHousingType are parsed;
    :New buyer is returned;
stop
else([User failed to provide correct parameters])
    :EstateEase displays an error;
stop
@enduml
