@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddSellerCommandParser" as AddSellerCommandParser LOGIC_COLOR
participant ":AddHouseCommandParser" as AddHouseCommandParser LOGIC_COLOR
participant "a:AddSellerCommand" as AddSellerCommand LOGIC_COLOR
participant "commandResult:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute(addSeller n/John Doe p/98765432 \n\
e/johnd@example.com type/Hdb street/Clementi Ave 2 blk/311 \n\
level/02 unitNo/25 postal/578578 price/999999999)
activate LogicManager

LogicManager -> AddressBookParser : parse(addSeller n/John Doe p/98765432 \n\
e/johnd@example.com type/Hdb street/Clementi Ave 2 blk/311 \n\
level/02 unitNo/25 postal/578578 price/999999999)
activate AddressBookParser

create AddSellerCommandParser
AddressBookParser -> AddSellerCommandParser
activate AddSellerCommandParser

AddSellerCommandParser --> AddressBookParser
deactivate AddSellerCommandParser

AddressBookParser -> AddSellerCommandParser : parse(n/John Doe p/98765432 \n\
e/johnd@example.com type/Hdb street/Clementi Ave 2 blk/311 \n\
level/02 unitNo/25 postal/578578 price/999999999)
activate AddSellerCommandParser

AddSellerCommandParser -> AddHouseCommandParser : checkValidity(...)
activate AddHouseCommandParser

AddHouseCommandParser --> AddSellerCommandParser
deactivate AddHouseCommandParser

create AddSellerCommand
AddSellerCommandParser -> AddSellerCommand
activate AddSellerCommand

AddSellerCommand --> AddSellerCommandParser
deactivate AddSellerCommand

AddSellerCommandParser --> AddressBookParser : a
deactivate AddSellerCommandParser

AddSellerCommandParser -[hidden]-> AddressBookParser
destroy AddSellerCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> AddSellerCommand : execute()
activate AddSellerCommand

AddSellerCommand -> Model : addSeller(seller)
activate Model

Model --> AddSellerCommand
deactivate Model

create CommandResult
AddSellerCommand -> CommandResult
activate CommandResult

CommandResult --> AddSellerCommand
deactivate CommandResult

AddSellerCommand --> LogicManager : commandResult
deactivate AddSellerCommand

[<-- LogicManager : commandResult
deactivate LogicManager
@enduml
