@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters add seller command;

if () then ([Seller and House Details Missing or Invalid])
    :Parse exception thrown;
    stop
else ([Details Valid])
    :Displays the success message;
endif

stop
@enduml
