@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":MatchBuyerCommandParser" as MatchBuyerCommandParser LOGIC_COLOR
participant "a:MatchBuyerCommand" as MatchBuyerCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("matchBuyer Alice Lim")
activate LogicManager

LogicManager -> AddressBookParser : parse("matchBuyer Alice Lim")
activate AddressBookParser

create MatchBuyerCommandParser
AddressBookParser -> MatchBuyerCommandParser
activate MatchBuyerCommandParser

MatchBuyerCommandParser --> AddressBookParser
deactivate MatchBuyerCommandParser

AddressBookParser -> MatchBuyerCommandParser : parseCommand("Alice Lim")
activate MatchBuyerCommandParser

create MatchBuyerCommand
MatchBuyerCommandParser -> MatchBuyerCommand
activate MatchBuyerCommand

MatchBuyerCommand --> MatchBuyerCommandParser
deactivate MatchBuyerCommand

MatchBuyerCommandParser --> AddressBookParser: a
deactivate MatchBuyerCommandParser

MatchBuyerCommandParser -[hidden]-> AddressBookParser
destroy MatchBuyerCommandParser

AddressBookParser --> LogicManager : a
deactivate AddressBookParser

LogicManager -> MatchBuyerCommand : execute(model)
activate MatchBuyerCommand

MatchBuyerCommand -> Model : updateFilteredSellerList(predicate)
activate Model

Model --> MatchBuyerCommand
deactivate Model

create CommandResult
MatchBuyerCommand -> CommandResult
activate CommandResult

CommandResult --> MatchBuyerCommand
deactivate CommandResult

MatchBuyerCommand --> LogicManager : result
deactivate MatchBuyerCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
