@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class "<<interface>>\nHouse" as House

Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person
Class Email
Class Name
Class Phone
Class Tag
Class PostalCode
Class UniqueHouseList
Class Street
Class Level
Class Block
Class Price
Class UnitNumber
Class Buyer extends Person
Class Seller extends Person
Class Condominium implements House
Class Hdb implements House
Class Landed implements House
Class Budget
Class HousingType

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "     ~* all" Person
'@@author
Person *--> "1" Name
Person *--> "1" Phone
Person *--> "1" Email
'@@author KhoonSun47
Person *--> "1" Tag
Hdb *--> "1" PostalCode
Condominium *--> "1" PostalCode
Landed *--> "1" PostalCode
Hdb *--> "1" UnitNumber
Condominium *--> "1" UnitNumber
Landed *--> "1" UnitNumber
'@@author felixchanyy
Hdb *--> "1" Street
Condominium *--> "1" Street
Landed *--> "1" Street
Hdb *--> "1" Price
Condominium *--> "1" Price
'@@author zengzihui
Landed *--> "1" Price
Condominium *--> "0..1" Block
Condominium *--> "1" Level
Hdb *--> "1" Block
Hdb *--> "1" Level
'@@author redcolorbicycle
Seller *--> "*" House : owns
Buyer *--> "1" Budget
Buyer *--> "      1" HousingType : prefers
'@@author
AddressBook *--> "1" UniqueHouseList
UniqueHouseList --> "~* all" House

Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I

Name -[hidden]right-> Phone

ModelManager --> "~* filtered" Person
ModelManager --> "~* filtered" House
@enduml
