@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Storage STORAGE_COLOR_T1
participant ":StorageManager" as StorageManager STORAGE_COLOR
participant ":AddressBookStorage" as AddressBookStorage STORAGE_COLOR
end box

[-> StorageManager : saveAddressBook(addressBook)
activate StorageManager

StorageManager -> AddressBookStorage : saveAddressBook(addressBook)
activate AddressBookStorage

alt file path is provided
    AddressBookStorage -> AddressBookStorage : saveAddressBook(addressBook, filePath)
    activate AddressBookStorage
    AddressBookStorage --> AddressBookStorage : File Saved
    deactivate AddressBookStorage
else default path
    AddressBookStorage -> AddressBookStorage : saveAddressBook(addressBook)
    activate AddressBookStorage
    AddressBookStorage --> AddressBookStorage : File Saved
    deactivate AddressBookStorage
end

AddressBookStorage --> StorageManager : saveSuccessful
deactivate AddressBookStorage

[<-- StorageManager : saveSuccessful
deactivate StorageManager
@enduml
